tasks:
  - init: |
      source venv1/bin/activate
      python manage.py migrate
    command: |
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
